name = "routine"
main = "src/index.js"
compatibility_date = "2024-01-01"

# D1 Database Binding
[[d1_databases]]
binding = "DB"
database_name = "routine"
database_id = "b4a77dc8-1607-407b-994c-2367687c39e6"

# R2 Bucket Binding
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "routine"